CREATE USER DB
  IDENTIFIED BY Q1w2e3r4
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS
  ACCOUNT UNLOCK;
GRANT "CONNECT" TO DB;
GRANT "RESOURCE" TO DB;
GRANT CREATE ANY DIRECTORY TO DB;