CREATE TABLE DB.COUNTRIES
  (
    COUNTRY_ID   NUMBER(3) NOT NULL, -- PRIMARY KEY
    COUNTRY VARCHAR(50) NOT NULL,
    CONSTRAINT COUNTRY_ID_PK PRIMARY KEY (COUNTRY_ID),
    CONSTRAINT COUNTRY_UK UNIQUE (COUNTRY)
  );
CREATE TABLE DB.ACCOUNTS
  (
    ACCOUNT_ID NUMBER(20) NOT NULL, -- PRIMARY KEY
    FIRST_NAME VARCHAR(40) NOT NULL,
    LAST_NAME  VARCHAR(40) NOT NULL,
    COUNTRY_ID NUMBER(3) NOT NULL, -- FK TO COUNTRY
    CONSTRAINT ACCOUNT_ID_PK PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT COUNTRY_ID_FK FOREIGN KEY (COUNTRY_ID) REFERENCES DB.COUNTRIES(COUNTRY_ID)
  );
CREATE INDEX NAMES_IX ON DB.ACCOUNTS
  (FIRST_NAME,LAST_NAME
  );
CREATE TABLE DB.CREDIT_CARDS
  (
    CREDIT_CARD_ID NUMBER(19) NOT NULL, -- PRIMARY KEY
    ACCOUNT_ID     NUMBER(20) NOT NULL, -- FK TO ACCOUNT
    CASH_AMOUNT    NUMBER(10,3) NOT NULL,
    CONSTRAINT CREDIT_CARD_ID_PK PRIMARY KEY (CREDIT_CARD_ID),
    CONSTRAINT ACCOUNT_ID_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES DB.ACCOUNTS(ACCOUNT_ID)
  );
CREATE TABLE DB.TRANSACTIONS
  (
    TRANSACTION_ID      NUMBER(20) NOT NULL, -- PRIMARY KEY
    FROM_CREDIT_CARD_ID NUMBER(19) NOT NULL, -- FK TO CC
    TO_CREDIT_CARD_ID   NUMBER(19) NOT NULL, -- FK TO CC
    TRANSACTION_AMOUNT  NUMBER(10,3) NOT NULL,
    CONSTRAINT TRANSACTION_ID_PK PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FCREDIT_CARD_ID_FK FOREIGN KEY (FROM_CREDIT_CARD_ID) REFERENCES DB.CREDIT_CARDS (CREDIT_CARD_ID),
    CONSTRAINT TCREDIT_CARD_ID_FK FOREIGN KEY (TO_CREDIT_CARD_ID) REFERENCES DB.CREDIT_CARDS (CREDIT_CARD_ID),
    CONSTRAINT CHECK_DESTINATION CHECK (FROM_CREDIT_CARD_ID != TO_CREDIT_CARD_ID)
  );
--CREATE SEQUENCES FOR TABLES
CREATE SEQUENCE DB.COUNTRIES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DB.ACCOUNTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DB.CREDIT_CARDS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DB.TRANSACTIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
